name: Check & Test

on: ["push", "pull_request"]

jobs:
  checks:
    name: "Check & Test python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10.0-rc.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: "scripts/install -D"
        shell: bash

      - name: "Run linting checks"
        run: "scripts/check"
        shell: bash

      - name: Pytest
        if: matrix.python-version != 3.9
        run: pytest

      - name: Pytest and coverage report
        if: matrix.python-version == 3.9
        run: pytest --cov=correios --cov-report=xml

      - name: Upload coverage report
        if: matrix.python-version == 3.9
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml