name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install the dependencies
        run: scripts/install -D
        shell: bash

      - name: Build package & docs
        run: scripts/build
        shell: bash

      - name: Publish to PyPI & deploy docs
        run: scripts/publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  create-github-release:
    name: Create github release
    runs-on: ubuntu-latest
    env:
      VERSION:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
